PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE

DIM        = 2

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE


USE_REACT = TRUE

# define the location of the FURNACE top directory
FURNACE_HOME  := ../../..

# This sets the EOS directory in Furnace/EOS
EOS_DIR     := helmholtz

# This sets the network directory in Furnace/Networks
NETWORK_DIR := triple_alpha_plus_cago

Bpack   := ./Make.package
Blocs   := .

include $(FURNACE_HOME)/Exec/Make.Furnace
