PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE

DIM        = 2

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE


USE_REACT = TRUE

# define the location of the LOGI top directory
LOGI_HOME  := ../../..

# This sets the EOS directory in Logi/EOS
EOS_DIR     := helmholtz

# This sets the network directory in Logi/Networks
NETWORK_DIR := triple_alpha_plus_cago

Bpack   := ./Make.package
Blocs   := .

include $(LOGI_HOME)/Exec/Make.Logi
